In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler

import warnings
warnings.filterwarnings("ignore")

In [3]:
file_path = r"D:\Self_project\social_media_dashboard\dataset\YouTubeDataset_withChannelElapsed_5000rows.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 5000
Columns: 27

In [5]:
#OR
df.shape

(5000, 27)

In [6]:
df.describe

<bound method NDFrame.describe of       index  totalviews/channelelapsedtime                 channelId  \
0         0                       0.165199  UCdzU3DSGzyWzN2118yd9X9g
1         1                       1.133820  UC0UnhAG47DRyVZGVcbhAXhQ
2         2                       0.668120  UCXjtAvK5P3wXBGh0vbGylzg
3         3                      25.653505  UCeKHMeUlcLNPLCLUfZUQI2w
4         4                      52.773778  UCNWPDyaWf2eAHnofFLSnEMg
...     ...                            ...                       ...
4995   4995                    3746.017471  UCRJQw-oofyAgFv3JlnIAxZQ
4996   4996                     240.344145  UCOwsbmIzp5OJNQjx6jOW2hg
4997   4997                       4.822536  UCVbIr9Qmt-r4isCQI963xgw
4998   4998                       0.268290  UCieL5ZyVlV6Sd9k2PnAN_Lw
4999   4999                       1.381268  UCWiu64eiOgwas4hzthJrubA

      videoCategoryId  channelViewCount  likes/subscriber  views/subscribers  \
0                  22             14654          0.555556          95.111111
1                  10            105909          0.239130          59.326087
2                  27             48265          0.023669          10.289941
3                  26           2116722          0.007301           0.884178
4                  20           1649075          0.004545          10.004545
...               ...               ...               ...                ...
4995               24         359351710          0.068418          49.490211
4996               24          13693848          1.710724        1080.989228
4997               10            329167         -1.000000          -1.000000
4998               20             12131          0.700000         304.100000
4999               22             77572          0.384817          37.869110

      videoCount  subscriberCount      videoId  ...  comments/views  \
0             30               18  --DwgB78t-c  ...        0.000000
1             51              184  --NZRkXBV7k  ...        0.000183
2             72              338  --hoQ2sGG4M  ...        0.000575
3            172            22051  --sBoaqBlzA  ...        0.000513
4           2777              220  --7h1S4neDM  ...        0.000000
...          ...              ...          ...  ...             ...
4995        1651           689911  -3ka09heHGI  ...        0.000028
4996         120             8262  -3qdOEVzZeg  ...        0.000277
4997           9                0  -3WTQtlgBtI  ...        0.000000
4998          43               10  -3K7UZ-DUpk  ...        0.000987
4999          14              382  -3s2skY-Nmo  ...        0.000968

      totvideos/videocount  elapsedtime  videoLikeCount  videoDislikeCount  \
0               488.466667        50040              10                  1
1              2076.647059        22080              44                  3
2               670.347222        71544               8                  1
3             12306.523256        54096             161                  6
4               593.833273        30120               1                  0
...                    ...          ...             ...                ...
4995         217657.001817        35352           47202              20685
4996         114115.400000        54480           14134               1316
4997          36574.111111        29184              48                  1
4998            282.116279        32952               7                  1
4999           5540.857143        21576             147                  8

      dislikes/subscriber  totviews/totsubs  views/elapsedtime  \
0                0.055556        814.111111           0.034213
1                0.016304        575.592391           0.494384
2                0.002959        142.795858           0.048613
3                0.000272         95.992109           0.360415
4                0.000000       7495.795455           0.073074
...                   ...               ...                ...
4995             0.029982        520.866764         965.824876
4996             0.159283       1657.449528         163.934159
4997            -1.000000         -1.000000           0.079359
4998             0.100000       1213.100000           0.092286
4999             0.020942        203.068063           0.670467

                videoPublished  VideoCommentCount
0     2012-01-19T18:38:28.000Z                  0
1     2015-03-30T04:04:40.000Z                  2
2     2009-08-07T06:51:10.000Z                  2
3     2011-08-04T01:07:38.000Z                 10
4     2014-04-29T15:44:44.000Z                  0
...                        ...                ...
4995  2013-09-23T03:30:01.000Z                952
4996  2011-07-18T20:07:19.000Z               2478
4997  2014-06-06T20:24:41.000Z                  0
4998  2014-01-01T04:41:22.000Z                  3
4999  2015-04-20T01:16:36.000Z                 14

[5000 rows x 27 columns]>

In [7]:
df.head(5)

,index,totalviews/channelelapsedtime,channelId,videoCategoryId,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,...,comments/views,totvideos/videocount,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount
0,0,0.165199,UCdzU3DSGzyWzN2118yd9X9g,22,14654,0.555556,95.111111,30,18,--DwgB78t-c,...,0.000000,488.466667,50040,10,1,0.055556,814.111111,0.034213,2012-01-19T18:38:28.000Z,0
1,1,1.133820,UC0UnhAG47DRyVZGVcbhAXhQ,10,105909,0.239130,59.326087,51,184,--NZRkXBV7k,...,0.000183,2076.647059,22080,44,3,0.016304,575.592391,0.494384,2015-03-30T04:04:40.000Z,2
2,2,0.668120,UCXjtAvK5P3wXBGh0vbGylzg,27,48265,0.023669,10.289941,72,338,--hoQ2sGG4M,...,0.000575,670.347222,71544,8,1,0.002959,142.795858,0.048613,2009-08-07T06:51:10.000Z,2
3,3,25.653505,UCeKHMeUlcLNPLCLUfZUQI2w,26,2116722,0.007301,0.884178,172,22051,--sBoaqBlzA,...,0.000513,12306.523256,54096,161,6,0.000272,95.992109,0.360415,2011-08-04T01:07:38.000Z,10
4,4,52.773778,UCNWPDyaWf2eAHnofFLSnEMg,20,1649075,0.004545,10.004545,2777,220,--7h1S4neDM,...,0.000000,593.833273,30120,1,0,0.000000,7495.795455,0.073074,2014-04-29T15:44:44.000Z,0

In [8]:
df.columns.tolist()

['index',
 'totalviews/channelelapsedtime',
 'channelId',
 'videoCategoryId',
 'channelViewCount',
 'likes/subscriber',
 'views/subscribers',
 'videoCount',
 'subscriberCount',
 'videoId',
 'dislikes/views',
 'channelelapsedtime',
 'comments/subscriber',
 'likes/views',
 'channelCommentCount',
 'videoViewCount',
 'likes/dislikes',
 'comments/views',
 'totvideos/videocount',
 'elapsedtime',
 'videoLikeCount',
 'videoDislikeCount',
 'dislikes/subscriber',
 'totviews/totsubs',
 'views/elapsedtime',
 'videoPublished',
 'VideoCommentCount']

In [9]:
df.isnull().sum()

index                            0
totalviews/channelelapsedtime    0
channelId                        0
videoCategoryId                  0
channelViewCount                 0
likes/subscriber                 0
views/subscribers                0
videoCount                       0
subscriberCount                  0
videoId                          0
dislikes/views                   0
channelelapsedtime               0
comments/subscriber              0
likes/views                      0
channelCommentCount              0
videoViewCount                   0
likes/dislikes                   0
comments/views                   0
totvideos/videocount             0
elapsedtime                      0
videoLikeCount                   0
videoDislikeCount                0
dislikes/subscriber              0
totviews/totsubs                 0
views/elapsedtime                0
videoPublished                   0
VideoCommentCount                0
dtype: int64

In [10]:
df.drop_duplicates()

,index,totalviews/channelelapsedtime,channelId,videoCategoryId,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,...,comments/views,totvideos/videocount,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount
0,0,0.165199,UCdzU3DSGzyWzN2118yd9X9g,22,14654,0.555556,95.111111,30,18,--DwgB78t-c,...,0.000000,488.466667,50040,10,1,0.055556,814.111111,0.034213,2012-01-19T18:38:28.000Z,0
1,1,1.133820,UC0UnhAG47DRyVZGVcbhAXhQ,10,105909,0.239130,59.326087,51,184,--NZRkXBV7k,...,0.000183,2076.647059,22080,44,3,0.016304,575.592391,0.494384,2015-03-30T04:04:40.000Z,2
2,2,0.668120,UCXjtAvK5P3wXBGh0vbGylzg,27,48265,0.023669,10.289941,72,338,--hoQ2sGG4M,...,0.000575,670.347222,71544,8,1,0.002959,142.795858,0.048613,2009-08-07T06:51:10.000Z,2
3,3,25.653505,UCeKHMeUlcLNPLCLUfZUQI2w,26,2116722,0.007301,0.884178,172,22051,--sBoaqBlzA,...,0.000513,12306.523256,54096,161,6,0.000272,95.992109,0.360415,2011-08-04T01:07:38.000Z,10
4,4,52.773778,UCNWPDyaWf2eAHnofFLSnEMg,20,1649075,0.004545,10.004545,2777,220,--7h1S4neDM,...,0.000000,593.833273,30120,1,0,0.000000,7495.795455,0.073074,2014-04-29T15:44:44.000Z,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,3746.017471,UCRJQw-oofyAgFv3JlnIAxZQ,24,359351710,0.068418,49.490211,1651,689911,-3ka09heHGI,...,0.000028,217657.001817,35352,47202,20685,0.029982,520.866764,965.824876,2013-09-23T03:30:01.000Z,952
4996,4996,240.344145,UCOwsbmIzp5OJNQjx6jOW2hg,24,13693848,1.710724,1080.989228,120,8262,-3qdOEVzZeg,...,0.000277,114115.400000,54480,14134,1316,0.159283,1657.449528,163.934159,2011-07-18T20:07:19.000Z,2478
4997,4997,4.822536,UCVbIr9Qmt-r4isCQI963xgw,10,329167,-1.000000,-1.000000,9,0,-3WTQtlgBtI,...,0.000000,36574.111111,29184,48,1,-1.000000,-1.000000,0.079359,2014-06-06T20:24:41.000Z,0
4998,4998,0.268290,UCieL5ZyVlV6Sd9k2PnAN_Lw,20,12131,0.700000,304.100000,43,10,-3K7UZ-DUpk,...,0.000987,282.116279,32952,7,1,0.100000,1213.100000,0.092286,2014-01-01T04:41:22.000Z,3
4999,4999,1.381268,UCWiu64eiOgwas4hzthJrubA,22,77572,0.384817,37.869110,14,382,-3s2skY-Nmo,...,0.000968,5540.857143,21576,147,8,0.020942,203.068063,0.670467,2015-04-20T01:16:36.000Z,14

In [11]:
df.shape

(5000, 27)

In [12]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['index', 'totalviews/channelelapsedtime', 'channelId', 'videoCategoryId', 'channelViewCount', 'likes/subscriber', 'views/subscribers', 'videoCount', 'subscriberCount', 'videoId', 'dislikes/views', 'channelelapsedtime', 'comments/subscriber', 'likes/views', 'channelCommentCount', 'videoViewCount', 'likes/dislikes', 'comments/views', 'totvideos/videocount', 'elapsedtime', 'videoLikeCount', 'videoDislikeCount', 'dislikes/subscriber', 'totviews/totsubs', 'views/elapsedtime', 'videoPublished', 'VideoCommentCount']

In [15]:
numeric_columns = df.select_dtypes(
    include=np.number
).columns

print("Numerical columns:")
for column in numeric_columns:
    print(column)

Numerical columns:
index
totalviews/channelelapsedtime
videoCategoryId
channelViewCount
likes/subscriber
views/subscribers
videoCount
subscriberCount
dislikes/views
channelelapsedtime
comments/subscriber
likes/views
channelCommentCount
videoViewCount
likes/dislikes
comments/views
totvideos/videocount
elapsedtime
videoLikeCount
videoDislikeCount
dislikes/subscriber
totviews/totsubs
views/elapsedtime
VideoCommentCount