In [18]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler

import warnings
warnings.filterwarnings("ignore")

In [19]:
file_path = r"C:\Users\sutra\Downloads\archive\YouTubeDataset_withChannelElapsed.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [20]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 575610
Columns: 27

In [21]:
#OR
df.shape

(575610, 27)

In [22]:
df.describe

<bound method NDFrame.describe of          index  totalviews/channelelapsedtime                 channelId  \
0            0                       0.165199  UCdzU3DSGzyWzN2118yd9X9g
1            1                       1.133820  UC0UnhAG47DRyVZGVcbhAXhQ
2            2                       0.668120  UCXjtAvK5P3wXBGh0vbGylzg
3            3                      25.653505  UCeKHMeUlcLNPLCLUfZUQI2w
4            4                      52.773778  UCNWPDyaWf2eAHnofFLSnEMg
...        ...                            ...                       ...
575605  575605                     259.123802  UCoBsEPCif0cJr0XoH9vKVsA
575606  575606                       0.322689  UC2AFyZm1gI81faexxhq5Mzg
575607  575607                       2.174518  UCXRQyRCOq8SwupXXqQ3mgAA
575608  575608                       5.044453  UCtWqVyrfT_CrVeNx0UM4RjQ
575609  575609                       2.980623  UCrgYGNrCj4C9imt2NCneznA

        videoCategoryId  channelViewCount  likes/subscriber  \
0                    22             14654          0.555556
1                    10            105909          0.239130
2                    27             48265          0.023669
3                    26           2116722          0.007301
4                    20           1649075          0.004545
...                 ...               ...               ...
575605               10          25342567          0.011829
575606                2             30599          2.333333
575607               28            103855          0.227273
575608               24            363927          0.069519
575609               20            141210          0.245345

        views/subscribers  videoCount  subscriberCount      videoId  ...  \
0               95.111111          30               18  --DwgB78t-c  ...
1               59.326087          51              184  --NZRkXBV7k  ...
2               10.289941          72              338  --hoQ2sGG4M  ...
3                0.884178         172            22051  --sBoaqBlzA  ...
4               10.004545        2777              220  --7h1S4neDM  ...
...                   ...         ...              ...          ...  ...
575605           2.577992        3783             7270  2YwZKSyX5Pg  ...
575606        4989.000000          15                3  2Y8Rtvd8cHc  ...
575607         276.909091          61               22  2YhOrl3fzCM  ...
575608          10.331551         258              187  2Y3a5eS_q2s  ...
575609          17.361192          16             2417  2Y4e4gwEhaU  ...

        comments/views  totvideos/videocount  elapsedtime  videoLikeCount  \
0             0.000000            488.466667        50040              10
1             0.000183           2076.647059        22080              44
2             0.000575            670.347222        71544               8
3             0.000513          12306.523256        54096             161
4             0.000000            593.833273        30120               1
...                ...                   ...          ...             ...
575605        0.000534           6699.066085        49752              86
575606       -1.000000           2039.933333        93745               7
575607        0.000164           1702.540984        41496               5
575608        0.002070           1410.569767        38352              13
575609        0.003956           8825.625000        47112             593

        videoDislikeCount  dislikes/subscriber  totviews/totsubs  \
0                       1             0.055556        814.111111
1                       3             0.016304        575.592391
2                       1             0.002959        142.795858
3                       6             0.000272         95.992109
4                       0             0.000000       7495.795455
...                   ...                  ...               ...
575605                  2             0.000275       3485.910179
575606                  2             0.666667      10199.666667
575607                  9             0.409091       4720.681818
575608                  1             0.005348       1946.133690
575609                 48             0.019859         58.423666

        views/elapsedtime            videoPublished  VideoCommentCount
0                0.034213  2012-01-19T18:38:28.000Z                  0
1                0.494384  2015-03-30T04:04:40.000Z                  2
2                0.048613  2009-08-07T06:51:10.000Z                  2
3                0.360415  2011-08-04T01:07:38.000Z                 10
4                0.073074  2014-04-29T15:44:44.000Z                  0
...                   ...                       ...                ...
575605           0.376708  2012-02-01T04:01:17.000Z                 10
575606           0.159657  2007-01-25T14:38:49.000Z                 -1
575607           0.146809  2013-01-10T07:20:03.000Z                  1
575608           0.050375  2013-05-20T18:33:03.000Z                  4
575609           0.890686  2012-05-21T05:57:05.000Z                166

[575610 rows x 27 columns]>

In [23]:
df.head(5)

,index,totalviews/channelelapsedtime,channelId,videoCategoryId,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,...,comments/views,totvideos/videocount,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount
0,0,0.165199,UCdzU3DSGzyWzN2118yd9X9g,22,14654,0.555556,95.111111,30,18,--DwgB78t-c,...,0.000000,488.466667,50040,10,1,0.055556,814.111111,0.034213,2012-01-19T18:38:28.000Z,0
1,1,1.133820,UC0UnhAG47DRyVZGVcbhAXhQ,10,105909,0.239130,59.326087,51,184,--NZRkXBV7k,...,0.000183,2076.647059,22080,44,3,0.016304,575.592391,0.494384,2015-03-30T04:04:40.000Z,2
2,2,0.668120,UCXjtAvK5P3wXBGh0vbGylzg,27,48265,0.023669,10.289941,72,338,--hoQ2sGG4M,...,0.000575,670.347222,71544,8,1,0.002959,142.795858,0.048613,2009-08-07T06:51:10.000Z,2
3,3,25.653505,UCeKHMeUlcLNPLCLUfZUQI2w,26,2116722,0.007301,0.884178,172,22051,--sBoaqBlzA,...,0.000513,12306.523256,54096,161,6,0.000272,95.992109,0.360415,2011-08-04T01:07:38.000Z,10
4,4,52.773778,UCNWPDyaWf2eAHnofFLSnEMg,20,1649075,0.004545,10.004545,2777,220,--7h1S4neDM,...,0.000000,593.833273,30120,1,0,0.000000,7495.795455,0.073074,2014-04-29T15:44:44.000Z,0

In [24]:
df.columns.tolist()

['index',
 'totalviews/channelelapsedtime',
 'channelId',
 'videoCategoryId',
 'channelViewCount',
 'likes/subscriber',
 'views/subscribers',
 'videoCount',
 'subscriberCount',
 'videoId',
 'dislikes/views',
 'channelelapsedtime',
 'comments/subscriber',
 'likes/views',
 'channelCommentCount',
 'videoViewCount',
 'likes/dislikes',
 'comments/views',
 'totvideos/videocount',
 'elapsedtime',
 'videoLikeCount',
 'videoDislikeCount',
 'dislikes/subscriber',
 'totviews/totsubs',
 'views/elapsedtime',
 'videoPublished',
 'VideoCommentCount']

In [25]:
df.isnull().sum()

index                            0
totalviews/channelelapsedtime    0
channelId                        0
videoCategoryId                  0
channelViewCount                 0
likes/subscriber                 0
views/subscribers                0
videoCount                       0
subscriberCount                  0
videoId                          0
dislikes/views                   0
channelelapsedtime               0
comments/subscriber              0
likes/views                      0
channelCommentCount              0
videoViewCount                   0
likes/dislikes                   0
comments/views                   0
totvideos/videocount             0
elapsedtime                      0
videoLikeCount                   0
videoDislikeCount                0
dislikes/subscriber              0
totviews/totsubs                 0
views/elapsedtime                0
videoPublished                   0
VideoCommentCount                0
dtype: int64

In [26]:
df.drop_duplicates()

,index,totalviews/channelelapsedtime,channelId,videoCategoryId,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,...,comments/views,totvideos/videocount,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount
0,0,0.165199,UCdzU3DSGzyWzN2118yd9X9g,22,14654,0.555556,95.111111,30,18,--DwgB78t-c,...,0.000000,488.466667,50040,10,1,0.055556,814.111111,0.034213,2012-01-19T18:38:28.000Z,0
1,1,1.133820,UC0UnhAG47DRyVZGVcbhAXhQ,10,105909,0.239130,59.326087,51,184,--NZRkXBV7k,...,0.000183,2076.647059,22080,44,3,0.016304,575.592391,0.494384,2015-03-30T04:04:40.000Z,2
2,2,0.668120,UCXjtAvK5P3wXBGh0vbGylzg,27,48265,0.023669,10.289941,72,338,--hoQ2sGG4M,...,0.000575,670.347222,71544,8,1,0.002959,142.795858,0.048613,2009-08-07T06:51:10.000Z,2
3,3,25.653505,UCeKHMeUlcLNPLCLUfZUQI2w,26,2116722,0.007301,0.884178,172,22051,--sBoaqBlzA,...,0.000513,12306.523256,54096,161,6,0.000272,95.992109,0.360415,2011-08-04T01:07:38.000Z,10
4,4,52.773778,UCNWPDyaWf2eAHnofFLSnEMg,20,1649075,0.004545,10.004545,2777,220,--7h1S4neDM,...,0.000000,593.833273,30120,1,0,0.000000,7495.795455,0.073074,2014-04-29T15:44:44.000Z,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575605,575605,259.123802,UCoBsEPCif0cJr0XoH9vKVsA,10,25342567,0.011829,2.577992,3783,7270,2YwZKSyX5Pg,...,0.000534,6699.066085,49752,86,2,0.000275,3485.910179,0.376708,2012-02-01T04:01:17.000Z,10
575606,575606,0.322689,UC2AFyZm1gI81faexxhq5Mzg,2,30599,2.333333,4989.000000,15,3,2Y8Rtvd8cHc,...,-1.000000,2039.933333,93745,7,2,0.666667,10199.666667,0.159657,2007-01-25T14:38:49.000Z,-1
575607,575607,2.174518,UCXRQyRCOq8SwupXXqQ3mgAA,28,103855,0.227273,276.909091,61,22,2YhOrl3fzCM,...,0.000164,1702.540984,41496,5,9,0.409091,4720.681818,0.146809,2013-01-10T07:20:03.000Z,1
575608,575608,5.044453,UCtWqVyrfT_CrVeNx0UM4RjQ,24,363927,0.069519,10.331551,258,187,2Y3a5eS_q2s,...,0.002070,1410.569767,38352,13,1,0.005348,1946.133690,0.050375,2013-05-20T18:33:03.000Z,4
575609,575609,2.980623,UCrgYGNrCj4C9imt2NCneznA,20,141210,0.245345,17.361192,16,2417,2Y4e4gwEhaU,...,0.003956,8825.625000,47112,593,48,0.019859,58.423666,0.890686,2012-05-21T05:57:05.000Z,166

In [27]:
df.shape

(575610, 27)

In [28]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['index', 'totalviews/channelelapsedtime', 'channelId', 'videoCategoryId', 'channelViewCount', 'likes/subscriber', 'views/subscribers', 'videoCount', 'subscriberCount', 'videoId', 'dislikes/views', 'channelelapsedtime', 'comments/subscriber', 'likes/views', 'channelCommentCount', 'videoViewCount', 'likes/dislikes', 'comments/views', 'totvideos/videocount', 'elapsedtime', 'videoLikeCount', 'videoDislikeCount', 'dislikes/subscriber', 'totviews/totsubs', 'views/elapsedtime', 'videoPublished', 'VideoCommentCount']

In [31]:
numeric_columns = df.select_dtypes(
    include=np.number
).columns

print("Numerical columns:")
for column in numeric_columns:
    print(column)

Numerical columns:
index
totalviews/channelelapsedtime
videoCategoryId
channelViewCount
likes/subscriber
views/subscribers
videoCount
subscriberCount
dislikes/views
channelelapsedtime
comments/subscriber
likes/views
channelCommentCount
videoViewCount
likes/dislikes
comments/views
totvideos/videocount
elapsedtime
videoLikeCount
videoDislikeCount
dislikes/subscriber
totviews/totsubs
views/elapsedtime
VideoCommentCount
17

In [32]:
df["Like_Rate"] = (
    df["likes"] / df["views"]
) * 100

KeyError: 'likes'